### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by Nezteb** [Squadrick/typehere#2]
Since [learning about this project on Lobsters](https://lobste.rs/s/opvfah/typehere_cc), I haven't been able to see any content on this projects homepage. [Even the latest archive.org snapshots look blank](https://web.archive.org/web/20231119020558/https://typehere.cc/). 🤔

I figured I should report it just in case. 😅

**Comment by Squadrick** [comment]
It doesn't contain anything.

You should see a text area, try typing something. Close the tab and go back to the website.

It's a trivially simple website. Read this article if you wanna know why I wrote it: https://squadrick.dev/journal/typehere.html

**Comment by Nezteb** [comment]
Ah when I posted this issue initially I just got a grey loading screen. Now things seem to load fine; initially I suspected a HN/Reddit hug of death.

Closing!
